import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {getCurrentUser} from "@/services/authService";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getCurrentUser(); // Vérifie si l'utilisateur est connecté

  return (
      <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* Affiche du Header uniquement si l'utilisateur est connecté */}
      {user && <Header />}
      <main>{children}</main>
      </body>
      </html>
  );
}
